export const plans = [
  {
    name: 'Free',
    price: 'Free',
    priceId: null,
    planType: 'FREE',
    description: 'For testing',
    features: [
      '5 monthly credits',
      'Basic platform access',
      'AI code generator',
      'Community support',
    ],
    credits: 5,
    isFree: true,
  },
  // {
  //   name: 'Basic',
  //   price: 'R$ 29',
  //   priceId: 'STRIPE_PRICE_ID_BASIC',
  //   planType: 'BASIC',
  //   description: 'To get started',
  //   features: [
  //     '20 monthly credits',
  //     'Platform access',
  //     'Email support',
  //     'AI code generator',
  //   ],
  //   credits: 20,
  // },
  {
    name: 'Pro',
    price: '$ 39,90',
    priceId: 'STRIPE_PRICE_ID_PRO',
    planType: 'PRO',
    description: 'To grow',
    features: [
      '50 monthly credits',
      'Everything from Basic',
      'Priority support',
      'Advanced features',
    ],
    popular: true,
    credits: 50,
  },
];
