import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy | CrazyNator',
  description: 'Privacy policy and data protection of the CrazyNator platform in compliance with LGPD',
};

export default function PrivacyPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <div className="space-y-8">
        <header className="text-center">
          <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
          <p className="text-muted-foreground">
            Last updated: {new Date().toLocaleDateString('en-US')}
          </p>
          <div className="mt-4 p-3 bg-blue-50 dark:bg-blue-950/20 border border-blue-200 dark:border-blue-800 rounded-lg">
            <p className="text-sm text-blue-700 dark:text-blue-300">
              <strong>LGPD Compliance:</strong> This policy is in compliance with the General Data Protection Law (Law No. 13.709/2018).
            </p>
          </div>
        </header>

        <div className="prose prose-neutral dark:prose-invert max-w-none">
          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">1. Data Controller</h2>
            <p>
              CrazyNator (&quot;we&quot;, &quot;our&quot; or &quot;us&quot;) is the controller of your personal data collected through this platform. We are responsible for deciding how and why your personal data is processed.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">2. Personal Data Collected</h2>
            
            <div className="space-y-3">
              <h3 className="text-lg font-medium">2.1 Identification Data</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Full name:</strong> For experience personalization</li>
                <li><strong>Email address:</strong> For authentication and communication</li>
                <li><strong>Profile picture:</strong> Optional, via OAuth providers</li>
                <li><strong>Unique user ID:</strong> Automatically generated by the system</li>
              </ul>
              
              <h3 className="text-lg font-medium">2.2 Usage Data</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Created projects:</strong> Code, prompts and configurations</li>
                <li><strong>Message history:</strong> AI interactions</li>
                <li><strong>Generated files:</strong> Code and project structures</li>
                <li><strong>Credit consumption:</strong> For usage control and billing</li>
                <li><strong>Access logs:</strong> IP, browser, session date/time</li>
              </ul>
              
              <h3 className="text-lg font-medium">2.3 Technical Data</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>IP address:</strong> For security and geolocation</li>
                <li><strong>Device information:</strong> Browser, OS, resolution</li>
                <li><strong>Cookies and similar technologies:</strong> For functionality and analytics</li>
                <li><strong>Sandbox URLs:</strong> For code execution in isolated environment</li>
              </ul>

              <h3 className="text-lg font-medium">2.4 Payment Data</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Billing information:</strong> Processed via Stripe</li>
                <li><strong>Transaction history:</strong> For financial control</li>
                <li><strong>Subscription status:</strong> For access control</li>
              </ul>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">3. Legal Basis for Processing</h2>
            <p>We process your personal data based on the following legal bases provided in LGPD:</p>
            
            <div className="space-y-3">
              <h3 className="text-lg font-medium">3.1 Contract Performance (Art. 7, V)</h3>
              <p>
                Data necessary to provide our services as agreed in our Terms of Service.
              </p>
              
              <h3 className="text-lg font-medium">3.2 Legitimate Interest (Art. 7, IX)</h3>
              <p>
                To improve our services, prevent fraud and ensure platform security.
              </p>
              
              <h3 className="text-lg font-medium">3.3 Consent (Art. 7, I)</h3>
              <p>
                For non-essential cookies, direct marketing and optional features.
              </p>
              
              <h3 className="text-lg font-medium">3.4 Legal Obligation Compliance (Art. 7, II)</h3>
              <p>
                To meet legal requirements, such as tax data retention and judicial investigations.
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">4. Processing Purposes</h2>
            
            <div className="space-y-3">
              <h3 className="text-lg font-medium">4.1 Service Provision</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>Authentication and account management</li>
                <li>AI-assisted code generation</li>
                <li>Project storage and synchronization</li>
                <li>Payment processing and billing</li>
                <li>Technical support and customer service</li>
              </ul>
              
              <h3 className="text-lg font-medium">4.2 Improvements and Development</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>Usage analysis to improve features</li>
                <li>Training and improvement of AI models</li>
                <li>Development of new features</li>
                <li>Performance optimization</li>
              </ul>
              
              <h3 className="text-lg font-medium">4.3 Security and Compliance</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>Fraud prevention and malicious activities</li>
                <li>Security monitoring</li>
                <li>Compliance with legal obligations</li>
                <li>Investigation of Terms of Service violations</li>
              </ul>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">5. Data Sharing</h2>
            
            <div className="space-y-3">
              <h3 className="text-lg font-medium">5.1 Service Providers</h3>
              <p>We share data with trusted service providers:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Clerk:</strong> Authentication and user management</li>
                <li><strong>Stripe:</strong> Payment processing</li>
                <li><strong>E2B:</strong> Sandbox code execution</li>
                <li><strong>Vercel/AWS:</strong> Hosting and infrastructure</li>
                <li><strong>OpenAI/Anthropic:</strong> AI services (anonymized data)</li>
              </ul>
              
              <h3 className="text-lg font-medium">5.2 Legal Requirements</h3>
              <p>
                We may disclose personal data when required by law, court order or competent authority.
              </p>
              
              <h3 className="text-lg font-medium">5.3 We Don't Sell Data</h3>
              <p>
                <strong>We never sell, rent or commercialize your personal data</strong> to third parties for marketing purposes.
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">6. Data Retention</h2>
            
            <div className="space-y-3">
              <h3 className="text-lg font-medium">6.1 Retention Periods</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li><strong>Account data:</strong> While account is active + 5 years after deletion</li>
                <li><strong>Projects and code:</strong> While account is active</li>
                <li><strong>Access logs:</strong> 12 months</li>
                <li><strong>Financial data:</strong> 5 years (legal obligation)</li>
                <li><strong>Analytics cookies:</strong> 24 months</li>
              </ul>
              
              <h3 className="text-lg font-medium">6.2 Automatic Deletion</h3>
              <p>
                Data is automatically deleted after retention periods, except when required by law.
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">7. International Transfer</h2>
            <p>
              Some of our service providers are located outside Brazil. We ensure these transfers meet LGPD requirements through:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Approved standard contractual clauses</li>
              <li>Adequacy certifications (Privacy Shield successors)</li>
              <li>Adequacy decisions when applicable</li>
              <li>Appropriate technical and organizational measures</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">8. Data Subject Rights (LGPD Art. 18)</h2>
            <p>
              You have the following rights regarding your personal data:
            </p>
            
            <div className="grid md:grid-cols-2 gap-4 mt-4">
              <div className="p-4 border rounded-lg">
                <h3 className="font-medium mb-2">🔍 Confirmation and Access</h3>
                <p className="text-sm">Confirm if we process your data and access information about processing</p>
              </div>
              <div className="p-4 border rounded-lg">
                <h3 className="font-medium mb-2">✏️ Correction</h3>
                <p className="text-sm">Correct incomplete, inaccurate or outdated data</p>
              </div>
              <div className="p-4 border rounded-lg">
                <h3 className="font-medium mb-2">🗑️ Deletion</h3>
                <p className="text-sm">Request deletion of unnecessary data or data processed improperly</p>
              </div>
              <div className="p-4 border rounded-lg">
                <h3 className="font-medium mb-2">📱 Portability</h3>
                <p className="text-sm">Request data portability to another provider</p>
              </div>
              <div className="p-4 border rounded-lg">
                <h3 className="font-medium mb-2">🚫 Opposition</h3>
                <p className="text-sm">Object to processing based on legitimate interest</p>
              </div>
              <div className="p-4 border rounded-lg">
                <h3 className="font-medium mb-2">ℹ️ Information</h3>
                <p className="text-sm">Obtain information about entities we share data with</p>
              </div>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">9. How to Exercise Your Rights</h2>
            <p>
              To exercise any of the rights above, you can:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Access privacy settings in your account</li>
              <li>Contact us through the platform support channel</li>
              <li>Send email to our privacy team</li>
              <li>Use the specific form on our privacy page</li>
            </ul>
            <p className="mt-3 p-3 bg-yellow-50 dark:bg-yellow-950/20 border border-yellow-200 dark:border-yellow-800 rounded">
              <strong>Response time:</strong> We will respond to your request within 15 days, as established by LGPD.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">10. Data Security</h2>
            <p>
              We implement appropriate technical and organizational measures to protect your data:
            </p>
            
            <div className="space-y-3">
              <h3 className="text-lg font-medium">10.1 Technical Measures</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>Encryption in transit (TLS 1.3) and at rest (AES-256)</li>
                <li>Multi-factor authentication available</li>
                <li>Role-based access controls</li>
                <li>Continuous security monitoring</li>
                <li>Secure backups and recovery testing</li>
              </ul>
              
              <h3 className="text-lg font-medium">10.2 Organizational Measures</h3>
              <ul className="list-disc pl-6 space-y-1">
                <li>Regular employee privacy training</li>
                <li>Internal data protection policies</li>
                <li>Confidentiality agreements with providers</li>
                <li>Regular system and process auditing</li>
                <li>Incident response plan</li>
              </ul>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">11. Security Incidents</h2>
            <p>
              In case of an incident that may pose a risk to data subjects' rights and freedoms:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>We will notify ANPD within 72 hours of becoming aware</li>
              <li>We will communicate affected data subjects when the risk is high</li>
              <li>We will take immediate measures to mitigate damages</li>
              <li>We will document the incident and measures taken</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">12. Minors</h2>
            <p>
              Our services are directed at individuals over 18 years old. We do not intentionally collect data from minors. If we become aware that we have collected data from a minor, we will delete this information immediately.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">13. Changes to This Policy</h2>
            <p>
              We may update this policy periodically. Significant changes will be communicated at least 30 days in advance through:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Email to your registered account</li>
              <li>Prominent notice on our platform</li>
              <li>Push notification (if enabled)</li>
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">14. Data Protection Officer (DPO)</h2>
            <div className="p-4 bg-muted rounded-lg">
              <p>
                <strong>Our Data Protection Officer is available to clarify questions about this policy and the processing of your personal data.</strong>
              </p>
              <p className="mt-2 text-sm">
                Contact: Available through platform support channels
              </p>
            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">15. Data Protection Authority</h2>
            <p>
              If we are unable to resolve your concern, you have the right to file a complaint with the National Data Protection Authority (ANPD):
            </p>
            <div className="p-4 bg-muted rounded-lg">
              <p><strong>ANPD - National Data Protection Authority</strong></p>
              <p>Website: <a href="https://www.gov.br/anpd" target="_blank" rel="noopener" className="text-blue-600 hover:underline">www.gov.br/anpd</a></p>
              <p>Citizen channel: Available on the official website</p>
            </div>
          </section>
        </div>

        <div className="mt-8 p-6 bg-muted rounded-lg">
          <p className="text-sm text-muted-foreground">
            <strong>Commitment:</strong> This Privacy Policy was developed in compliance with the General Data Protection Law (LGPD - Law No. 13.709/2018) and other applicable regulations. Our commitment is to transparency and protection of your personal data.
          </p>
        </div>

        <div className="text-center space-x-4">
          <Link 
            href="/" 
            className="inline-flex items-center px-4 py-2 bg-primary text-primary-foreground rounded-md hover:bg-primary/90 transition-colors"
          >
            Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}